title: "Gerardo Quiroz"
email: gerardo@example.com
description: >- 
  Portafolio profesional de Gerardo Quiroz, desarrollador full stack.
baseurl: "" 
url: "https://tuusuario.github.io" 
theme: minima
